//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class repartosssEntities : DbContext
    {
        public repartosssEntities()
            : base("name=repartosssEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administradors { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<pedido> pedidoes { get; set; }
        public virtual DbSet<repartidor> repartidors { get; set; }
    }
}
