//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepartosEntities : DbContext
    {
        public RepartosEntities()
            : base("name=RepartosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administradors { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<pedido> pedidoes { get; set; }
        public virtual DbSet<repartidor> repartidors { get; set; }
    }
}
