//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjecteM15Part1MVVMv0._1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int idPedido { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string Entregado { get; set; }
        public string Decripcion { get; set; }
        public string cliente_DNI { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<factura> factura { get; set; }
    }
}
