//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webserviceRepartos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int idFactura { get; set; }
        public bool Entrega { get; set; }
        public int Pedido_idPedido { get; set; }
        public string Pedido_Cliente_DNI { get; set; }
        public int Repartidor_idRepartidor { get; set; }
        public int Administrador_idAdministrador { get; set; }
    
        public virtual administrador administrador { get; set; }
        public virtual pedido pedido { get; set; }
        public virtual repartidor repartidor { get; set; }
    }
}
